-- E-Mail-Vorlagen als JSON in settings speichern
INSERT INTO settings (key, value) VALUES 
  ('email_template_new_order_bereichsleiter_subject', 'Neue Bestellung zur Freigabe: {{orderTitle}}'),
  ('email_template_new_order_bereichsleiter_body', '<h2 style="color: #ea580c;">Neue Bestellung zur Freigabe</h2><p>Hallo {{recipientName}},</p><p>Eine neue Bestellung wartet auf Ihre Freigabe.</p><div style="background: #fff7ed; padding: 16px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #ea580c;"><p><strong>Bestellung:</strong> {{orderTitle}}</p><p><strong>Eingereicht von:</strong> {{creatorName}}</p></div><p>Bitte melden Sie sich im BANF System an, um die Bestellung zu prüfen.</p>'),
  ('email_template_new_order_kommandant_subject', 'Bestellung erfordert Ihre Freigabe: {{orderTitle}}'),
  ('email_template_new_order_kommandant_body', '<h2 style="color: #dc2626;">Neue Bestellung erfordert Ihre Freigabe</h2><p>Hallo {{recipientName}},</p><p>Eine Bestellung mit hohem Betrag wurde eingereicht und erfordert Ihre Freigabe.</p><div style="background: #fef2f2; padding: 16px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #dc2626;"><p><strong>Bestellung:</strong> {{orderTitle}}</p></div><p>Bitte melden Sie sich im BANF System an, um die Bestellung zu prüfen.</p>'),
  ('email_template_approval_subject', 'Bestellung freigegeben: {{orderTitle}}'),
  ('email_template_approval_body', '<h2 style="color: #16a34a;">Bestellung freigegeben</h2><p>Hallo {{creatorName}},</p><p>Ihre Bestellung wurde freigegeben.</p><div style="background: #f3f4f6; padding: 16px; border-radius: 8px; margin: 16px 0;"><p><strong>Bestellung:</strong> {{orderTitle}}</p><p><strong>Betrag:</strong> {{orderAmount}}</p><p><strong>Freigegeben von:</strong> {{approverName}} ({{approverRole}})</p></div><p>Die Bestellung wartet ggf. noch auf weitere Freigaben.</p>'),
  ('email_template_final_approval_subject', 'Bestellung genehmigt: {{orderTitle}}'),
  ('email_template_final_approval_body', '<h2 style="color: #16a34a;">Bestellung genehmigt</h2><p>Hallo {{creatorName}},</p><p>Ihre Bestellung wurde endgültig genehmigt.</p><div style="background: #f0fdf4; padding: 16px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #16a34a;"><p><strong>Bestellung:</strong> {{orderTitle}}</p><p><strong>Betrag:</strong> {{orderAmount}}</p><p><strong>Genehmigt von:</strong> {{approverName}} ({{approverRole}})</p></div><p style="color: #16a34a; font-weight: bold;">Die Bestellung kann nun ausgeführt werden.</p>'),
  ('email_template_rejection_subject', 'Bestellung abgelehnt: {{orderTitle}}'),
  ('email_template_rejection_body', '<h2 style="color: #dc2626;">Bestellung abgelehnt</h2><p>Hallo {{creatorName}},</p><p>Ihre Bestellung wurde leider abgelehnt.</p><div style="background: #fef2f2; padding: 16px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #dc2626;"><p><strong>Bestellung:</strong> {{orderTitle}}</p><p><strong>Betrag:</strong> {{orderAmount}}</p><p><strong>Abgelehnt von:</strong> {{approverName}} ({{approverRole}})</p><p><strong>Grund:</strong> {{rejectionReason}}</p></div><p>Bei Fragen wenden Sie sich bitte an Ihren Vorgesetzten.</p>')
ON CONFLICT (key) DO NOTHING;