export type SettingsSection =
  | 'freigaben'
  | 'eskalation'
  | 'erinnerungen'
  | 'pdf'
  | 'email-empfaenger'
  | 'system'
  | 'zugriffsrechte'
  | 'mitglieder'
  | 'funktionen'
  | 'email-vorlagen'
  | 'email-design'
  | 'leihgeraete'
  | 'leihvertraege'
  | 'probleme'
  | 'aufgaben'
  | 'modul-berechtigungen'
  | 'tagesordnung';
